### ISSUE TITLE
安装mtphoto pull fail，超时时间短？

### ISSUE THREAD

**Issue by SkyAzure** [qwerty00007/xchart#2]
Failed to pull image "mtphotos/mt-photos:v1.16.1@sha256:5affcdefbfa5bbac89b14537fc898092f5abe33fc52fdbf6b9b1af48cc5a4e97": rpc error: code = Unknown desc = context deadline exceeded

**Comment by qwerty00007** [comment]
这个是网络原因，pull 镜像超时了。

**Comment by SkyAzure** [comment]
网络问题，已解决
