### ISSUE TITLE
moviepilot 设置-服务-同步cookiecloud 没有显示

### ISSUE THREAD

**Issue by Jesse-Fan** [qwerty00007/xchart#3]
用自定义程序部署就有显示 直接用xchart是没有的
并且格外有个疑问就是 xchart对应应用程序版本是不是需要和moviepilot的docker版本一一对应呢？

**Comment by qwerty00007** [comment]
这个我也不清楚，是用的mp的原版镜像，标贴用的是latest，每次提示更新，手动更新镜像，重启应用就可以更新了
