### ISSUE TITLE
如何自定义qbittorrent的ip ?

### ISSUE THREAD

**Issue by AAEE86** [qwerty00007/xchart#4]

**Comment by qwerty00007** [comment]
因 truenas 官方后续会弃用 k3s 这个库不再添加新的功能。
你这个需求，可以通过官方的自定义安装应用，在 externalInterfaces 这个位置选择网卡，配置 ip

**Comment by AAEE86** [comment]
感谢答复，我从 truenas 官方看到了 后续的更新计划，后续将改用Docker / Compose，期待更新。
